# Generated by Django 6.0.5 on 2026-05-19 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('PERSONAL', 'Personal'), ('CORPORATE', 'Corporate')], default='PERSONAL', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_issue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_feedback', to='core.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_response', to='core.feedback')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_response', to='core.issue')),
                ('response_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100)),
                ('found_issue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issue', to='core.review'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('REVIEWING', 'Reviewing'), ('ISSUE_FOUND', 'Issue Found'), ('APPLY_REVIEW', 'Apply Review'), ('DONE', 'Done')], default='TO_DO', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_task', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PRIVATE', 'private'), ('PUBLIC', 'public')], default='PRIVATE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subtask', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_subtask', to='core.task')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_review', to='core.task'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('FILE', 'File'), ('URL', 'URL'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('REPOSITORY', 'Repository')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachment', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assign', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_event_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_cursor', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('REVIEWER', 'Reviewer'), ('WORKER', 'Worker')], default='OWNER', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('leaved_at', models.DateTimeField(blank=True, null=True)),
                ('member_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_member', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_MOVED', 'Task Moved'), ('REVIEW_REQUESTED', 'Review Requested'), ('REVIEW_APPROVED', 'Review Approved'), ('REVIEW_REJECTED', 'Review Rejected'), ('ISSUE_CREATED', 'Issue Created'), ('ISSUE_UPDATED', 'Issue Updated'), ('FEEDBACK_CREATED', 'Feedback Created'), ('FEEDBACK_RESPONSE', 'Feedback Response'), ('WORKSPACE_JOINED', 'Workspace Joined'), ('TASK_ASSIGNED', 'Task Assigned'), ('EXPIRE_ALERT', 'Expire Alert')], max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_activity', to='core.issue')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_activity', to='core.review')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_activity', to='core.task')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_activity', to='core.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['issue', 'feedback_by'], name='core_feedba_issue_i_208679_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['issue', 'feedback', 'response_by'], name='core_respon_issue_i_57726a_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'created_by'], name='core_subtas_task_id_7d9ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'type'], name='core_subtas_task_id_684ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['task', 'reviewer'], name='core_review_task_id_4650c2_idx'),
        ),
        migrations.AddIndex(
            model_name='assign',
            index=models.Index(fields=['task', 'assigned_to'], name='core_assign_task_id_30f53f_idx'),
        ),
        migrations.AddIndex(
            model_name='usereventcursor',
            index=models.Index(fields=['user', 'workspace'], name='core_userev_user_id_97ae5f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'assigned_by'], name='core_task_workspa_c9542c_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'member_of'], name='core_member_workspa_2687d7_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'type'], name='core_activi_user_id_1a21af_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['workspace'], name='core_activi_workspa_98928e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['task'], name='core_activi_task_id_ff2a39_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['issue'], name='core_activi_issue_i_550034_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['review'], name='core_activi_review__c7258b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='core_activi_created_5c6490_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['is_processed'], name='core_activi_is_proc_5f7132_idx'),
        ),
    ]
