# Generated by Django 6.0.5 on 2026-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('REVIEWER', 'Reviewer'), ('WORKER', 'Worker')], default='OWNER', max_length=100),
        ),
    ]
