# Generated by Django 6.0.5 on 2026-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
