# Generated by Django 6.0.5 on 2026-05-21 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subtask_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_issue', to='core.task'),
            preserve_default=False,
        ),
    ]
