# Generated by Django 6.0.5 on 2026-05-21 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_issue_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='core_feedba_issue_i_208679_idx',
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='core_respon_issue_i_57726a_idx',
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['feedback_by'], name='core_feedba_feedbac_ed00e3_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['feedback', 'response_by'], name='core_respon_feedbac_5128ca_idx'),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='response',
            name='issue',
        ),
    ]
