# Generated by Django 6.0.5 on 2026-05-21 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_feedback_core_feedba_issue_i_208679_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='core_feedba_feedbac_ed00e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='core_respon_feedbac_5128ca_idx',
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_feedback', to='core.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_response', to='core.task'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['task', 'feedback_by'], name='core_feedba_task_id_bbd228_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['task', 'feedback', 'response_by'], name='core_respon_task_id_5d66ba_idx'),
        ),
    ]
