# Generated by Django 6.0.5 on 2026-05-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_feedback_core_feedba_feedbac_ed00e3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_MOVED', 'Task Moved'), ('TASK_ASSIGNED', 'Task Assigned'), ('REVIEW_REQUESTED', 'Review Requested'), ('REVIEW_APPROVED', 'Review Approved'), ('REVIEW_REJECTED', 'Review Rejected'), ('ISSUE_CREATED', 'Issue Created'), ('ISSUE_UPDATED', 'Issue Updated'), ('FEEDBACK_CREATED', 'Feedback Created'), ('FEEDBACK_RESPONSE', 'Feedback Response'), ('WORKSPACE_JOINED', 'Workspace Joined'), ('TASK_ASSIGNED', 'Task Assigned'), ('EXPIRE_ALERT', 'Expire Alert')], max_length=100),
        ),
    ]
