# Generated by Django 6.0.5 on 2026-05-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_activitylog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('ISSUE_FOUND', 'Issue Found'), ('APPLY_REVIEW', 'Apply Review'), ('DONE', 'Done')], default='TO_DO', max_length=100),
        ),
    ]
