# Generated by Django 6.0.5 on 2026-05-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'todo'), ('PROGRESS', 'progress'), ('ISSUE', 'issue'), ('REVIEW', 'review'), ('DONE', 'done')], default='TO_DO', max_length=100),
        ),
    ]
