# Generated by Django 6.0.5 on 2026-05-22 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='role',
            field=models.CharField(choices=[('REVIEWER', 'Reviewer'), ('WORKER', 'Worker')], default='WORKER', max_length=100),
        ),
        migrations.AddIndex(
            model_name='assign',
            index=models.Index(fields=['task', 'assigned_to', 'role'], name='core_assign_task_id_a43528_idx'),
        ),
    ]
