# Generated by Django 6.0.5 on 2026-05-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_assign_role_assign_core_assign_task_id_a43528_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_COMPLETED', 'Task completed'), ('TASK_ASSIGNED', 'Task Assigned'), ('REVIEW_REQUESTED', 'Review Requested'), ('REVIEW_APPROVED', 'Review Approved'), ('REVIEW_REJECTED', 'Review Rejected'), ('ISSUE_CREATED', 'Issue Created'), ('ISSUE_UPDATED', 'Issue Updated'), ('FEEDBACK_CREATED', 'Feedback Created'), ('FEEDBACK_RESPONSE', 'Feedback Response'), ('WORKSPACE_JOINED', 'Workspace Joined'), ('EXPIRE_ALERT', 'Expire Alert')], max_length=100),
        ),
    ]
