# Generated by Django 6.0.5 on 2026-05-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_activitylog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='found_issue',
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('ISSUE', 'issue'), ('DONE', 'done')], default='DONE', max_length=100),
        ),
    ]
