# Generated by Django 6.0.5 on 2026-05-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_review_found_issue_alter_review_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='core_activi_issue_i_550034_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='core_activi_review__c7258b_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='core_activi_is_proc_5f7132_idx',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='review',
        ),
    ]
