# Generated by Django 6.0.5 on 2026-05-25 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_activitylog_core_activi_issue_i_550034_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='review',
        ),
        migrations.AddField(
            model_name='feedback',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_feedback', to='core.issue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='issue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='issue_response', to='core.issue'),
            preserve_default=False,
        ),
    ]
