# Generated by Django 6.0.5 on 2026-05-29 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_issue_review_feedback_issue_response_issue'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='response',
            name='core_respon_task_id_5d66ba_idx',
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.feedback'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
